home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

quickpay/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib.auth.models import User
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp.admin import OTPAdminSite
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import StaticViewSitemap


from home import views

class OTPAdmin(OTPAdminSite):
    pass

admin_site = OTPAdmin(name="OTPAdmin")

admin_site.register(User)
admin_site.register(TOTPDevice)

sitemaps = {
    'static': StaticViewSitemap
}

urlpatterns = [
    path('django_admin/', admin.site.urls),
    path('admin/', admin_site.urls),

    path('', include('home.urls', namespace='home')),
    path('about', views.about, name='about'),
    path('quickpayloans', views.service, name='quickpayloans'),
    path('contact', views.contact, name='contact'),
    path('faq', views.faq, name='faq'),

    path('quickpayloans/<slug:slug>', views.service_detail, name='service_detail'),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots.txt', include('robots.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.forms import ModelForm, TextInput, Textarea
from django.urls import reverse


class Company(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True,max_length=100)
    mobile = models.CharField(blank=True,max_length=15)
    email = models.CharField(blank=True,max_length=50)
    image = models.ImageField(blank=True,upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    status=models.CharField(max_length=10,choices=STATUS)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Company'

    def __str__(self):
        return self.title

class Service(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    short_detail = models.CharField(max_length=500)
    detail = RichTextUploadingField(blank=True)
    icon = models.ImageField(upload_to='images/')
    icon_alt = models.CharField(max_length=160)    
    image = models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=160)
    slug = models.SlugField(max_length=255, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Services'
    
    def get_absolute_url(self):
        return reverse('service_detail', args=[self.slug])
    
    def __str__(self):
        return self.title
    
class About(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    image = models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=160)
    detail = RichTextUploadingField(blank=True)
    short_detail = models.CharField(max_length=250)
    status = models.CharField(max_length=10, choices=STATUS)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'About'

    def __str__(self):
        return self.title

class Slider(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    image = models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100)
    hero_text = models.CharField(max_length=100)
    status = models.CharField(max_length=10, choices=STATUS)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.hero_text


class Vision(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    image = models.ImageField(upload_to='images/')
    alt = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    short_detail = models.CharField(max_length=250)

    class Meta:
        verbose_name_plural = 'Vision'

    def __str__(self):
        return self.title
    


class ContactMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    first_name = models.CharField(blank=True, max_length=50)
    last_name = models.CharField(blank=True, max_length=50)
    email = models.CharField(blank=True, max_length=50)
    phone = models.CharField(blank=True, max_length=20)
    subject = models.CharField(blank=True, max_length=50)
    message = models.TextField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name


class ContactForm(ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['first_name', 'last_name', 'email', 'phone', 'subject', 'message']
        widgets = {
            'first_name': TextInput(attrs={'class': 'input', 'placeholder': 'First Name'}),
            'last_name': TextInput(attrs={'class': 'input', 'placeholder': 'Last Name'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'Phone Number'}),
            'message': Textarea(attrs={'class': 'input', 'placeholder': 'Your Message', 'rows': '5'}),
        }


class FAQ(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    question_number = models.IntegerField()
    question = models.CharField(max_length=200)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'FAQs'
    
    def __str__(self):
        return self.question

home/views.py
from email.mime import image
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from . models import FAQ, ContactForm, ContactMessage, Service, Slider, About, Vision

def home(request):
    services = Service.objects.order_by('-created')[:6]
    slider = Slider.objects.all
    about = About.objects.all()
    return render(request, 'index.html', {'slider': slider, 'services': services, 'about': about})


def about(request):
    about = About.objects.all
    vision = Vision.objects.all
    services = Service.objects.order_by('-created')[:6]
    return render(request, 'about.html', {'about': about, 'vision': vision, 'services': services})


def service(request):
    services = Service.objects.all()
    about = About.objects.all()
    return render(request, 'service.html', {'services': services, 'about': about})

def service_detail(request, slug):
    service = get_object_or_404(Service, slug=slug)
    about = About.objects.all()
    return render(request, 'service_detail.html', {'service': service, 'about': about})


def contact(request):
    if request.method == 'POST':  # check post
        form = ContactForm(request.POST)
        if form.is_valid():
            data = ContactMessage()  # create relation with model
            data.first_name = form.cleaned_data['first_name']  # get form input data
            data.last_name = form.cleaned_data['last_name']  # get form input data
            data.email = form.cleaned_data['email']
            data.phone = form.cleaned_data['phone']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()  # save data to table
            messages.success(
                request, "Your message has been sent. Thank you for your message! We'll reach out as soon as possible.")
            return HttpResponseRedirect('/contact')
    form = ContactForm
    about = About.objects.all()
    services = Service.objects.order_by('-created')[:6]
    return render(request, 'contact.html', {'form': form, 'about': about, 'services': services})


def faq(request):
    if request.method == 'POST':  # check post
        form = ContactForm(request.POST)
        if form.is_valid():
            data = ContactMessage()  # create relation with model
            data.first_name = form.cleaned_data['first_name']  # get form input data
            data.last_name = form.cleaned_data['last_name']  # get form input data
            data.email = form.cleaned_data['email']
            data.phone = form.cleaned_data['phone']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()  # save data to table
            messages.success(
                request, "Your message has been sent. Thank you for your message! We'll reach out as soon as possible.")
            return HttpResponseRedirect('/contact')
    faq = FAQ.objects.all()
    form = ContactForm
    about = About.objects.all()
    services = Service.objects.order_by('-created')[:6]
    return render(request, 'faq.html', {'faq': faq, 'form': form, 'about': about, 'services': services})

home/templates/footer.html
{% load static %}

<!-- Footer Start -->
<footer id="rs-footer" class="rs-footer style1 footer-home4-style">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-12 col-sm-12 md-mb-10">
                    <div class="footer-logo mb-40">
                        <a href="{% url 'home:home' %}"><img src="{% static 'assets/images/quick-pay-credit-logo.jpg' %}" alt="QuickPay Credit Limited Logo"></a>
                    </div>
                    {% for rs in about %}
                      <div class="textwidget white-color pb-40"><p>{{ rs.short_detail }}</p>
                      </div>
                      {% endfor %}
                      <ul class="footer-social md-mb-30">  
                          <li> 
                              <a href="https://www.facebook.com/quickpaycredit" target="_blank"><span><i class="fa fa-facebook"></i></span></a> 
                          </li>
                          <li> 
                              <a href="https://www.twitter.com/quickpaycredit" target="_blank"><span><i class="fa fa-twitter"></i></span></a> 
                          </li>

                          <li> 
                              <a href="https://www.instagram.com/quickpaycredit" target="_blank"><span><i class="fa fa-instagram"></i></span></a> 
                          </li>
                          <li>
                                                                   
                      </ul>
                </div>
                <div class="col-lg-3 col-md-12 col-sm-12 md-mb-10 pl-55 md-pl-15">
                    <h3 class="footer-title">Quick Links</h3>
                    <ul class="site-map">
                        <li><a href="{% url 'home:home' %}">Home</a></li>
                        <li><a href="{% url 'about' %}">About</a></li>
                        <li><a href="{% url 'quickpayloans' %}">QuickPay Loans</a></li>
                        <li><a href="{% url 'contact' %}">Contact</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-12 col-sm-12 md-mb-10">
                    <h3 class="footer-title">Contact Info</h3>
                    <ul class="address-widget">
                        <li>
                            <i class="flaticon-location"></i>
                            <div class="desc">Delta Corner Annex, Westlands, Nairobi</div>
                        </li>
                        <li>
                            <i class="flaticon-call"></i>
                            <div class="desc">
                               <a href="tel:+254723527197">+254 723 527197</a>
                            </div>
                        </li>
                        <li>
                            <i class="flaticon-email"></i>
                            <div class="desc">
                                <a href="mailto:info@quickpaycredit.com">info@quickpaycredit.com</a>
                            </div>
                        </li>
                        
                    </ul>
                </div>
                <div class="col-lg-3 col-md-12 col-sm-12">
                    <h3 class="footer-title">Newsletter</h3>
                    <p class="widget-desc white-color">Stay up to update with our latest news and products.</p>
                    <p>
                        <input type="email" name="EMAIL" placeholder="Your email address" required="">
                        <input type="submit" value="Subscribe Now">
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">                    
            <div class="row y-middle">
                <div class="col-lg-6 md-mb-10 text-lg-end text-center order-last">
                    <ul class="copy-right-menu">
                        <li><a href="{% url 'home:home' %}">Home</a></li>
                        <li><a href="{% url 'about' %}">About</a></li>
                        <li><a href="{% url 'faq' %}">Faqs</a></li>
                        <li><a href="{% url 'contact' %}">Contact</a></li>
                    </ul>
                </div>
                <div class="col-lg-6">
                    <div class="copyright text-lg-start text-center ">
                        <p>&copy; {% now 'Y' %} QuickPay Credit Limited. All Rights Reserved. Made By <a href="https://codeworldcreatives.com" target="_blank">Code World Creatives</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer End -->

home/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<!-- Slider Start -->
<div id="rs-slider" class="rs-slider slider3 rs-slider-style4 relative">
    {% for rs in slider %}
    <div class="bend niceties">
        <div id="nivoSlider" class="slides">
            <img src="{{ rs.image.url }}" alt="" title="#slide-1" />
        </div>
        <!-- Slide 1 -->
        <div id="slide-1" class="slider-direction">
            <div class="content-part text-center">
                <div class="container">
                    <div class="slider-des">
                        <div class="sl-subtitle">{{ rs.subtitle }}</div>
                        <h1 class="sl-title">{{ rs.hero_text }}</h1>
                    </div>
                    <ul class="slider-bottom">
                        <li><a class="readon consultant orange-slide" href="contact.html">Get Started</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<!-- Slider End -->

<!-- Services Section Start -->
<div id="rs-services" class="rs-services style6">
    <div class="container custom">
        <div class="rs-services style5 bg14 pt-95 pb-100 md-pt-65 md-pb-70">
            <div class="row margin-0">
                {% for rs in services %}
                <div class="col-lg-4 col-md-6 mb-25">
                   <div class="flip-box-inner">
                        <div class="flip-box-wrap">
                            <div class="front-part">
                               <div class="front-content-part">
                                    <div class="front-icon-part">
                                        <div class="icon-part">
                                            <img src="{{ rs.icon.url }}" alt="{{ rs.icon_alt }}"> 
                                        </div>
                                    </div>
                                    <div class="front-title-part">
                                        <h3 class="title"><a href="{{ rs.get_absolute_url }}">{{ rs.title }}</a></h3>
                                    </div>
                                    <div class="front-desc-part">
                                        <p>{{ rs.short_detail }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="back-part">
                                <div class="back-front-content">
                                    <div class="back-title-part">
                                        <h3 class="back-title"><a href="{{ rs.get_absolute_url }}">{{ rs.title }}</a></h3>
                                    </div>
                                    <div class="back-desc-part">
                                        <p class="back-desc">{{ rs.short_detail }}</p>
                                    </div>
                                    <div class="back-btn-part">
                                        <a class="readon view-more" href="{{ rs.get_absolute_url}}">View More</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                   </div> 
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<!-- Services Section End -->

{% endblock %}

home/templates/navbar.html
{% load static %}

<!--Full width header Start-->
<div class="full-width-header">
    <!--Header Start-->
    <header id="rs-header" class="rs-header style3">
        <!-- Topbar Area Start -->
        <div class="topbar-area style2">
            <div class="container custom">
                <div class="row-table">
                    <div class="col-cell">
                        <div class="header-logo">
                            <div class="logo-area">
                                <a href="{% url 'home:home' %}">
                                    <img class="normal-logo" src="{% static 'assets/images/quick-pay-credit-logo.jpg' %}" alt="QuickPay Credit Limited Logo">  
                                    <img class="sticky-logo" src="{% static 'assets/images/quick-pay-credit-logo.jpg' %}" alt="QuickPay Credit Limited Logo">
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-cell">
                        <div class="header-quote">
                            <ul class="rs-address-area">
                                <li class="address-list">
                                    <div class="info-icon">
                                        <i class="flaticon-location"></i>
                                    </div>
                                    <div class="info-content">
                                        <div class="info-title"><a href="#">Location</a></div>
                                        <div class="info-des">Delta Corner Annex, Westlands, Nairobi</div>
                                    </div>
                                </li>
                                <li class="address-list">
                                    <div class="info-icon">
                                        <i class="flaticon-email"></i>
                                    </div>
                                    <div class="info-content">
                                        <div class="info-title"><a href="#">Mail us</a></div>
                                        <div class="info-des"><a href="mailto:info@quickpaycredit.com">info@quickpaycredit.com</a></div>
                                    </div>
                                </li>
                                <li class="address-list">
                                    <div class="info-icon">
                                        <i class="flaticon-call"></i>
                                    </div>
                                    <div class="info-content">
                                        <div class="info-title"><a href="#">Call us</a></div>
                                        <div class="info-des"><a href="tel:+254723527197">+254 723 527 197</a></div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Topbar Area End -->

        <!-- Menu Start -->
        <div class="menu-area menu-sticky">
            <div class="container custom box-layout">
                <div class="row-table">
                    <div class="col-cell header-logo">                                  
                        <div class="logo-area">
                            <a href="{% url 'home:home' %}">
                                <img src="{% static 'assets/images/quick-pay-credit-logo.jpg' %}" alt="QuickPay Credit Limited Logo">  
                            </a>
                        </div>
                    </div>
                    <div class="col-cell menu-responsive">
                        <div class="rs-menu-area">
                            <div class="main-menu">
                                <nav class="rs-menu hidden-md">
                                    <ul class="nav-menu">
                                        <li class="rs-mega-menu">
                                            <a href="{% url 'home:home' %}">Home</a></li>
                                        <li><a href="{% url 'about' %}">About</a></li>
                                        <li class="menu-item-has-children">
                                            <a href="{% url 'quickpayloans' %}">QuickPay Loans</a>
                                            <ul class="sub-menu">
                                                {% for rs in services %}
                                                <li {% if service_detail.slug == rs.slug %} class="selected" {% endif %}><a href="{{ rs.get_absolute_url }}">{{ rs.title }}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                        <li><a href="{% url 'contact' %}">Contact</a></li>
                                    </ul> <!-- //.nav-menu -->
                                </nav>
                            </div> <!-- //.main-menu -->
                        </div>
                    </div>
                    <div class="col-cell rightbar-menu">
                        <div class="expand-btn-inner">
                            <ul>
                                <li class="humburger">
                                    <a id="nav-expander" class="nav-expander bar" href="#">
                                        <div class="bar">
                                            <span class="dot1"></span>
                                            <span class="dot2"></span>
                                            <span class="dot3"></span>
                                            <span class="dot4"></span>
                                            <span class="dot5"></span>
                                            <span class="dot6"></span>
                                            <span class="dot7"></span>
                                            <span class="dot8"></span>
                                            <span class="dot9"></span>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                            <div class="toolbar-sl-share">
                                <ul>
                                    <li><a href="https://www.facebook.com/quickpaycredit"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="https://www.twitter.com/quickpaycredit"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="https://www.instagram.com/quickpaycredit"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Menu End -->
        <!-- Canvas Menu start -->
        <nav class="right_menu_togle hidden-md">
            <div class="close-btn">
                <a id="nav-close" class="nav-close">
                    <div class="line">
                        <span class="line1"></span>
                        <span class="line2"></span>
                    </div>
                </a>
            </div>
            <div class="canvas-logo">
                <a href="{% url 'home:home' %}"><img src="{% static 'assets/images/quick-pay-credit-logo.jpg' %}" alt="QuickPay Credit Limited Logo"></a>
            </div>
            <div class="offcanvas-text">
                <p>QuickPayy Credit Limited - Your Guide To Financial Freedom</p>
            </div>
            <div class="media-img">
                <img src="{% static 'assets/images/off2.jpg' %}" alt="Images">
            </div>
            <div class="canvas-contact">
                <div class="address-area">
                    <div class="address-list">
                        <div class="info-icon">
                            <i class="flaticon-location"></i>
                        </div>
                        <div class="info-content">
                            <h4 class="title">Address</h4>
                            <em>Delta Corner Annex, Westlands, Nairobi</em>
                        </div>
                    </div>
                    <div class="address-list">
                        <div class="info-icon">
                            <i class="flaticon-email"></i>
                        </div>
                        <div class="info-content">
                            <h4 class="title">Email</h4>
                            <em><a href="mailto:info@quickpaycredit.com">info@quickpaycredit.com</a></em>
                        </div>
                     </div>
                    <div class="address-list">
                        <div class="info-icon">
                          <i class="flaticon-call"></i>
                        </div>
                        <div class="info-content">
                          <h4 class="title">Phone</h4>
                          <em>+254723527197</em>
                        </div>
                    </div>
                </div>
                <ul class="social">
                    <li><a href="https://www.facebook.com/quickpaycredit"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="https://www.twitter.com/quickpaycredit"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="https://www.instagram.com/quickpaycredit"><i class="fa fa-instagram"></i></a></li>
                </ul>
            </div>
        </nav>
        <!-- Canvas Menu end -->

        <!-- Canvas Mobile Menu start -->
        <nav class="right_menu_togle mobile-navbar-menu" id="mobile-navbar-menu">
            <div class="close-btn">
                <a id="nav-close2" class="nav-close">
                    <div class="line">
                        <span class="line1"></span>
                        <span class="line2"></span>
                    </div>
                </a>
            </div>
            <ul class="nav-menu">
                <li class="current-menu-item">
                    <a href="{% url 'home:home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li class="menu-item-has-children">
                    <a href="{% url 'quickpayloans' %}">QuickPay Loans</a>
                    <ul class="sub-menu">
                        {% for rs in services %}
                        <li {% if service_detail.slug == rs.slug %} class="selected" {% endif %}><a href="{{ rs.get_absolute_url }}">{{ rs.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
            </ul> <!-- //.nav-menu -->
            <div class="canvas-contact">
                  <div class="address-area">
                      <div class="address-list">
                          <div class="info-icon">
                              <i class="flaticon-location"></i>
                          </div>
                          <div class="info-content">
                              <h4 class="title">Address</h4>
                              <em>Delta Corner Annex, Westlands, Nairobi</em>
                          </div>
                      </div>
                      <div class="address-list">
                          <div class="info-icon">
                              <i class="flaticon-email"></i>
                          </div>
                          <div class="info-content">
                              <h4 class="title">Email</h4>
                              <em><a href="mailto:info@quickpaycredit.com">info@quickpaycredit.com</a></em>
                          </div>
                      </div>
                      <div class="address-list">
                          <div class="info-icon">
                              <i class="flaticon-call"></i>
                          </div>
                          <div class="info-content">
                              <h4 class="title">Phone</h4>
                              <em>+254723527197</em>
                          </div>
                      </div>
                  </div>
            </div>
        </nav>
        <!-- Canvas Menu end -->
    </header>
    <!--Header End-->
</div>
<!--Full width header End-->

home/templates/structured_data.html
<script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Corporation",
      "name": "QuickPay Credit Limited",
      "alternateName": "QuickPay Credit",
      "url": "https://www.quickpaycredit.com",
      "logo": "https://www.quickpaycredit.com/static/images/quickpaycredit_logo.png",
      "sameAs": [
        "https://facebook.com/quickpaycredit",
        "https://instagram.com/quickpaycredit",
        "https://twitter.com/quickpaycredit",
        "https://www.quickpaycredit.com"
      ]
    }
    </script>